### PR TITLE
[42] - Service throws exception if cache is full

### LINKED ISSUE #42: Refactor OpenWalletService
- IsNull
- Cache Full Exception

### PR DESCRIPTION
**Pull request by IvanSolaDelgado**
**Issue**
- Resolves #42 

**Solution**
- Now we throw an exception when the cache is full and we handle it with the Handler as we do with the other exceptions.

### CODE REVIEW

File: tests/app/Infrastructure/Controller/PostOpenWalletControllerTest.php [hunk 1]
```diff
@@ -35,44 +35,44 @@ public function throwsErrorWhenUserIdNotFound()
...
-        $response->assertExactJson(['description' => 'successful operation','wallet_id' => 'wallet_0']);
+        $response->assertStatus(Response::HTTP_INSUFFICIENT_STORAGE);
+        $response->assertExactJson(['description' => 'Cache is full']);
     }
 
     /**
      * @test
      */
-    public function ifGoodUserIdAndCacheIsFullThrowsError()
+    public function createsWalletWhenUserIsFound()
```
Comment (AsierAlba10) [inline tests/app/Infrastructure/Controller/PostOpenWalletControllerTest.php:62]: WhenUserExists?

**Review by AsierAlba10 — APPROVED** [review]
