### PR TITLE
[49] - Separate controller responsabilities

### LINKED ISSUE #49: Separate controller responsabilities
- Extract logic to service.
- Add Exception if user or wallet not found.

### PR DESCRIPTION
**Pull request by IvanSolaDelgado**
**Issue**
- Resolves #49 

**Solution**
- I have separated the logic from the controller to a service and within it I have covered the cases where the wallet or coin does not exist with exceptions.

**Notes**
- The request form is called CoinRequest since it is common for BuyCoin and SellCoin and therefore when I merge everything I will combine it and use the same Request for the two controllers PostBuyCoinController and PostSellCoinController.

### CODE REVIEW

File: app/Infrastructure/Controllers/PostSellCoinController.php [hunk 1]
```diff
@@ -2,49 +2,28 @@
...
-use App\Domain\DataSources\WalletDataSource;
+use App\Application\Exceptions\CoinNotFoundException;
+use App\Application\Exceptions\WalletNotFoundException;
+use App\Application\Services\SellCoinService;
 use App\Http\Requests\CoinRequest;
 use Illuminate\Http\JsonResponse;
 use Illuminate\Http\Response;
 use Illuminate\Routing\Controller as BaseController;
 
 class PostSellCoinController extends BaseController
```
Comment (AsierAlba10) [inline app/Infrastructure/Controllers/PostSellCoinController.php:13]: SellCoinController?

File: app/Infrastructure/Controllers/PostSellCoinController.php [hunk 2]
```diff
@@ -2,49 +2,28 @@
...
-        $this->coinDataSource = $coinDataSource;
-        $this->walletDataSource = $walletDataSource;
-    }
-
-    public function __invoke(CoinRequest $coinRequest): JsonResponse
+    /**
+     * @throws CoinNotFoundException
+     * @throws WalletNotFoundException
+     */
+    public function __invoke(CoinRequest $coinRequest, SellCoinService $sellCoinService): JsonResponse
```
Comment (AsierAlba10) [inline app/Infrastructure/Controllers/PostSellCoinController.php:19]: SellCoinRequest?

**Review by AsierAlba10 — APPROVED** [review]
