### PR TITLE
[20] - Open wallet service throws exception if user not found

### LINKED ISSUE #20: Add exception on user not found

### PR DESCRIPTION
**Pull request by IvanSolaDelgado**
**Issue**
- Resolves #20 

**Solution**
- Now we throw an exception in the service if the user has not been found and the exception handler is in charge of sending the corresponding json response.

### CODE REVIEW

File: app/Application/Services/OpenWalletService.php [hunk 1]
```diff
@@ -17,11 +17,14 @@ public function __construct(UserDataSource $userDataSource, WalletDataSource $wa
...
 
+    /**
+     * @throws UserNotFoundException
+     */
     public function createWallet(string $userId): ?string
     {
         $user = $this->userDataSource->findById($userId);
         if (is_null($user)) {
-            return null;
+            throw new UserNotFoundException('User not found');
```
Comment (AsierAlba10) [inline app/Application/Services/OpenWalletService.php:27]: What do you think to delete the message here and put it on the exception class??
```suggestion
            throw new UserNotFoundException();
```

File: app/Infrastructure/Exceptions/Handler.php [hunk 2]
```diff
@@ -37,4 +41,21 @@ public function register()
...
         });
     }
+
+    /**
+     * @param Request $request
+     * @param Throwable $userNotFoundExcepction
+     * @return Response
+     * @throws Throwable
+     */
+    public function render($request, Throwable $userNotFoundExcepction): Response
```
Comment (AsierAlba10) [inline app/Infrastructure/Exceptions/Handler.php:51]: Now you only have this exception and is correct, but when we scale this is not gonna be valid and we are gonna need a generic name.
```suggestion
    public function render($request, Throwable $userNotFoundException): Response
```

File: tests/app/Application/Services/OpenWalletServiceTest.php [hunk 3]
```diff
@@ -35,6 +36,8 @@ public function returnsNullWhenUserNotFound()
         $this->userDataSource->shouldReceive('findById')->with('123')->andReturnNull();
         $this->walletDataSource->shouldReceive('saveWalletInCache')->never();
 
+        $this->expectException(UserNotFoundException::class);
+
```
Comment (AsierAlba10) [inline tests/app/Application/Services/OpenWalletServiceTest.php:40]: Here you can test the exception message?

File: app/Infrastructure/Exceptions/Handler.php [hunk 4]
```diff
@@ -37,4 +41,21 @@ public function register()
...
+    {
+        if ($userNotFoundExcepction instanceof UserNotFoundException) {
+            return response()->json([
+                'description' => 'A user with the specified ID was not found'
```
Comment (AsierAlba10) [inline app/Infrastructure/Exceptions/Handler.php:55]: Instead of the string you can put the exception message

File: app/Infrastructure/Exceptions/UserNotFoundException.php [hunk 5]
```diff
@@ -0,0 +1,9 @@
+<?php
+
+namespace App\Infrastructure\Exceptions;
+
+use Exception;
+
+class UserNotFoundException extends Exception
+{
```
Comment (AsierAlba10) [inline app/Infrastructure/Exceptions/UserNotFoundException.php:8]: Here you can use a constructor and set a message and a status code... Research how 😄

File: app/Infrastructure/Exceptions/UserNotFoundException.php [hunk 6]
```diff
@@ -0,0 +1,9 @@
+<?php
+
+namespace App\Infrastructure\Exceptions;
```
Comment (AsierAlba10) [inline app/Infrastructure/Exceptions/UserNotFoundException.php:3]: We are using hexagonal architecture in this poyecto. Do u think this exception is on this layer??

**Review by AsierAlba10 — COMMENTED** [review]
Gooood, give it a second chance to the exceptions

**Review by AsierAlba10 — APPROVED** [review]
TOP
