### PR TITLE
[36] - Separate controller responsabilities

### LINKED ISSUE #36: Separate controller responsabilities
- Extract logic to service.
- Add Exception if user or wallet not found.

### PR DESCRIPTION
**Pull request by IvanSolaDelgado**
**Issue**
- Resolves #36 

**Solution**
- I have detached the controller logic to a service and have handled the cases where the coin or wallet is not found with exceptions.

### CODE REVIEW

File: app/Application/Exceptions/CoinNotFoundException.php [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+namespace App\Application\Exceptions;
+
+use Symfony\Component\HttpFoundation\Response;
+use Exception;
+
+class CoinNotFoundException extends Exception
+{
+    public function __construct()
+    {
+        parent::__construct('Coin not found', Response::HTTP_BAD_REQUEST);
```
Comment (AsierAlba10) [inline app/Application/Exceptions/CoinNotFoundException.php:12]: And an error 404?

File: app/Infrastructure/Controllers/PostBuyCoinController.php [hunk 2]
```diff
@@ -2,51 +2,27 @@
...
+use App\Application\Exceptions\CoinNotFoundException;
+use App\Application\Exceptions\WalletNotFoundException;
+use App\Application\Services\BuyCoinService;
 use App\Http\Requests\BuyCoinRequest;
 use Illuminate\Http\JsonResponse;
-use Illuminate\Http\Response;
 use Illuminate\Routing\Controller as BaseController;
+use Symfony\Component\HttpFoundation\Response;
 
 class PostBuyCoinController extends BaseController
```
Comment (AsierAlba10) [inline app/Infrastructure/Controllers/PostBuyCoinController.php:13]: BuyCoinController?

File: app/Infrastructure/Controllers/PostBuyCoinController.php [hunk 3]
```diff
@@ -2,51 +2,27 @@
...
-        $this->coinDataSource = $coinDataSource;
-        $this->walletDataSource = $walletDataSource;
-    }
-
-    public function __invoke(BuyCoinRequest $buyCoinRequest): JsonResponse
+    /**
+     * @throws WalletNotFoundException
+     * @throws CoinNotFoundException
+     */
+    public function __invoke(BuyCoinRequest $buyCoinRequest, BuyCoinService $buyCoinService): JsonResponse
```
Comment (AsierAlba10) [inline app/Infrastructure/Controllers/PostBuyCoinController.php:19]: Be careful where we put the FormRequest(I mean the directory)

**Review by AsierAlba10 — APPROVED** [review]
